
---
- hosts: webserver
  become: true
  tasks:
  - name: update the apt-get repo
    command: sudo apt-get update
  - name: Install maven on worker nodes
    package: name=maven state=present
  - name: Install docker using module
    package: name=docker-ce state=present
  - name: Start docker service
    service: name=docker state=started
